# Generated by Django 5.1.1 on 2024-10-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_remove_cruise_description_remove_cruise_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inforequest',
            old_name='message',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='relecloud.destination'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relecloud.cruise'),
        ),
    ]
