# Generated by Django 5.1.2 on 2024-10-11 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_rename_message_inforequest_notes_cruise_destinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
