# Generated by Django 5.1.1 on 2024-10-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_cruise_inforequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='destination',
        ),
    ]
